language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    on_success: never
    recipients:
      - haikalvidya@gmail.com
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: source
